//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public int UserId { get; set; }
        public int FunctionId { get; set; }
        public int ActionId { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual Function Function { get; set; }
        public virtual User User { get; set; }
    }
}
